name: Publish Docker image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
             echo ${{ github.repository }}
      - name: Import environment variables from .devops/config.env
        id: import-value
        env:
          ENV_FILE: ${{ github.workspace }}/.devops/config.env
        shell: bash
        run: |
          cat ${{ env.ENV_FILE }}
          while read line; do
          if [ "$(echo "$line" |xargs| grep -v -E '^#')" ]; then
            echo "$line" |xargs| grep -v -E '^#' >> $GITHUB_ENV
          fi
          done < ${{ env.ENV_FILE }}
      - uses: actions/checkout@v2
        name: checkout superset
        with:
          repository: far-eye/incubator-superset
          path: incubator-superset
          token: ${{ secrets.PAT_GITHUB }}
          ref: "$ref_value"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push to Docker Hub
        run: |
          ls -l
          docker build --target dev  -t saksham026/nlp-client:${{ env.RELEASE_VERSION }} ${{ github.workspace }}/incubator-superset/
          docker push saksham026/nlp-client:${{ env.RELEASE_VERSION }}
