name: Publish Docker image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
             echo ${{ github.repository }}
      - uses: actions/checkout@v2
        name: checkout superset
        with:
          repository: far-eye/incubator-superset
          path: incubator-superset
          token: ${{ secrets.PAT_GITHUB }}
          ref: fareye_master
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push to Docker Hub
        run: |
          ls -l
          docker build --target dev  -t saksham026/nlp-client:${{ env.RELEASE_VERSION }} ${{GITHUB_WORKSPACE}}/incubator-superset/
          docker push saksham026/nlp-client:${{ env.RELEASE_VERSION }}
